[tool.poetry]
name = "tower-service-catalog"
version = "0.1.0"
description = "Service catalog on top of Ansible Tower"
authors = ["Nicolas Marcq <nicolas.marcq@hpe.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.7"
djangorestframework = "^3.12.2"
Markdown = "^3.3.4"
mysqlclient = "^2.0.3"
PyYAML = "^5.4.1"
fontawesome-free = "^5.15.2"
celery = "^5.0.5"
django-celery-results = "^2.0.1"
towerlib = "^3.7.0"
Pillow = "^8.1.2"
django-guardian = "^2.3.0"
django-fsm = "^2.7.1"
django-celery-beat = "^2.2.0"
Pygments = "^2.8.1"
django-filter = "^2.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
